
package fr.cap.wikimnv.core.persistance;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "crudService", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", wsdlLocation = "http://172.20.100.173:8080/WikiMNV-Core-Persistance/ws/crudService?wsdl")
public class CrudService_Service
    extends Service
{

    private final static URL CRUDSERVICE_WSDL_LOCATION;
    private final static WebServiceException CRUDSERVICE_EXCEPTION;
    private final static QName CRUDSERVICE_QNAME = new QName("http://persistance.core.wikimnv.cap.fr/", "crudService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.20.100.173:8080/WikiMNV-Core-Persistance/ws/crudService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CRUDSERVICE_WSDL_LOCATION = url;
        CRUDSERVICE_EXCEPTION = e;
    }

    public CrudService_Service() {
        super(__getWsdlLocation(), CRUDSERVICE_QNAME);
    }

    public CrudService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CRUDSERVICE_QNAME, features);
    }

    public CrudService_Service(URL wsdlLocation) {
        super(wsdlLocation, CRUDSERVICE_QNAME);
    }

    public CrudService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CRUDSERVICE_QNAME, features);
    }

    public CrudService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CrudService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CrudService
     */
    @WebEndpoint(name = "crudServicePort")
    public CrudService getCrudServicePort() {
        return super.getPort(new QName("http://persistance.core.wikimnv.cap.fr/", "crudServicePort"), CrudService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CrudService
     */
    @WebEndpoint(name = "crudServicePort")
    public CrudService getCrudServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://persistance.core.wikimnv.cap.fr/", "crudServicePort"), CrudService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CRUDSERVICE_EXCEPTION!= null) {
            throw CRUDSERVICE_EXCEPTION;
        }
        return CRUDSERVICE_WSDL_LOCATION;
    }

}
