
package fr.cap.wikimnv.core.persistance;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "crudService", targetNamespace = "http://persistance.core.wikimnv.cap.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrudService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Object
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimer", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.Supprimer")
    @ResponseWrapper(localName = "supprimerResponse", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.SupprimerResponse")
    public Object supprimer(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Object
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sauver", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.Sauver")
    @ResponseWrapper(localName = "sauverResponse", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.SauverResponse")
    public Object sauver(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lire", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.Lire")
    @ResponseWrapper(localName = "lireResponse", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.LireResponse")
    public Object lire(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TypeStructure arg1)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lister", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.Lister")
    @ResponseWrapper(localName = "listerResponse", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.ListerResponse")
    public List<Object> lister(
        @WebParam(name = "arg0", targetNamespace = "")
        TypeStructure arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "faireRequete", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.FaireRequete")
    @ResponseWrapper(localName = "faireRequeteResponse", targetNamespace = "http://persistance.core.wikimnv.cap.fr/", className = "fr.cap.wikimnv.core.persistance.FaireRequeteResponse")
    public List<Object> faireRequete(
        @WebParam(name = "arg0", targetNamespace = "")
        Query arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Critere> arg1)
        throws MNVException_Exception
    ;

}
