
package fr.cap.wikimnv.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "MNVException", targetNamespace = "http://service.wikimnv.cap.fr/")
public class MNVException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private MNVException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public MNVException_Exception(String message, MNVException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public MNVException_Exception(String message, MNVException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: fr.cap.wikimnv.service.MNVException
     */
    public MNVException getFaultInfo() {
        return faultInfo;
    }

}
