
package fr.cap.wikimnv.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "profilService", targetNamespace = "http://service.wikimnv.cap.fr/", wsdlLocation = "http://172.20.100.133:8080/WikiMNV-Core-Admin/webservices/serviceProfil?wsdl")
public class ProfilService_Service
    extends Service
{

    private final static URL PROFILSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROFILSERVICE_EXCEPTION;
    private final static QName PROFILSERVICE_QNAME = new QName("http://service.wikimnv.cap.fr/", "profilService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.20.100.133:8080/WikiMNV-Core-Admin/webservices/serviceProfil?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROFILSERVICE_WSDL_LOCATION = url;
        PROFILSERVICE_EXCEPTION = e;
    }

    public ProfilService_Service() {
        super(__getWsdlLocation(), PROFILSERVICE_QNAME);
    }

    public ProfilService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROFILSERVICE_QNAME, features);
    }

    public ProfilService_Service(URL wsdlLocation) {
        super(wsdlLocation, PROFILSERVICE_QNAME);
    }

    public ProfilService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROFILSERVICE_QNAME, features);
    }

    public ProfilService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProfilService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProfilService
     */
    @WebEndpoint(name = "profilServicePort")
    public ProfilService getProfilServicePort() {
        return super.getPort(new QName("http://service.wikimnv.cap.fr/", "profilServicePort"), ProfilService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProfilService
     */
    @WebEndpoint(name = "profilServicePort")
    public ProfilService getProfilServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wikimnv.cap.fr/", "profilServicePort"), ProfilService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROFILSERVICE_EXCEPTION!= null) {
            throw PROFILSERVICE_EXCEPTION;
        }
        return PROFILSERVICE_WSDL_LOCATION;
    }

}
