
package fr.cap.wikimnv.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "profilService", targetNamespace = "http://service.wikimnv.cap.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProfilService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ranking", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.Ranking")
    @ResponseWrapper(localName = "rankingResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.RankingResponse")
    public int ranking(
        @WebParam(name = "arg0", targetNamespace = "")
        Profil arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @throws MNVException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "updateAvatar", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.UpdateAvatar")
    @ResponseWrapper(localName = "updateAvatarResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.UpdateAvatarResponse")
    public void updateAvatar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Profil arg1)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lister", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.Lister")
    @ResponseWrapper(localName = "listerResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.ListerResponse")
    public List<Object> lister(
        @WebParam(name = "arg0", targetNamespace = "")
        TypeStructure arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Object
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lire", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.Lire")
    @ResponseWrapper(localName = "lireResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.LireResponse")
    public Object lire(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        TypeStructure arg1)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countArticlesEcris", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.CountArticlesEcris")
    @ResponseWrapper(localName = "countArticlesEcrisResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.CountArticlesEcrisResponse")
    public int countArticlesEcris(
        @WebParam(name = "arg0", targetNamespace = "")
        Profil arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Object
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sauver", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.Sauver")
    @ResponseWrapper(localName = "sauverResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.SauverResponse")
    public Object sauver(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0)
        throws MNVException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Object
     * @throws MNVException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "supprimer", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.Supprimer")
    @ResponseWrapper(localName = "supprimerResponse", targetNamespace = "http://service.wikimnv.cap.fr/", className = "fr.cap.wikimnv.service.SupprimerResponse")
    public Object supprimer(
        @WebParam(name = "arg0", targetNamespace = "")
        Object arg0)
        throws MNVException_Exception
    ;

}
